// <auto-generated />
namespace s00157240Rad2016MVC1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class setupAdnRolesCreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(setupAdnRolesCreated));
        
        string IMigrationMetadata.Id
        {
            get { return "201610070920208_setupAdnRolesCreated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
